version: "3.8"

services:
  # REMOVED: mongodb service - using Atlas cloud instead!

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bookstore-backend
    ports:
      - "5000:5000"
    environment:
      # USE YOUR ATLAS CONNECTION STRING FROM THE IMAGE
      - MONGO_URI= mongodb+srv://dulinaranasinghe004_db_user:nethduli03@cluster0.xryraxz.mongodb.net/?appName=Cluster0
      - NODE_ENV=production
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bookstore-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

# REMOVED: mongodb_data volume - no longer needed!
