version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: book-store-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://dulinaranasinghe004_db_user:nethduli03@cluster0.xryraxz.mongodb.net/bookstore?appName=Cluster0
      - PORT=5000
      - NODE_ENV=development
    networks:
      - book-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: book-store-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - book-network

networks:
  book-network:
    driver: bridge
